name: "Create Docker images for microservices and push them to Docker Hub"

on:
  workflow_dispatch:

jobs:
  docker-build-push:
    name: Build and Push Docker Images
    strategy: 
      matrix:
        WORK_DIR:
          - egov-accesscontrol
          - egov-common-masters
          - egov-common-masters/src/main/resources/db
          - egov-data-uploader
          - egov-data-uploader/src/main/resources/db
          # - egov-enc-service
          # - egov-enc-service/src/main/resources/db
          # - egov-filestore
          # - egov-filestore/src/main/resources/db
          # - egov-idgen
          # - egov-idgen/src/main/resources/db
          # - egov-indexer
          # - egov-indexer/src/main/resources/db
          # - egov-localization
          # - egov-localization/src/main/resources/db
          # - egov-location
          # - egov-location/src/main/resources/db
          # - egov-mdms-service
          # - egov-notification-mail
          # - egov-notification-sms
          # - egov-otp
          # - egov-otp/src/main/resources/db
          # - egov-persister
          # - egov-pg-service
          # - egov-pg-service/src/main/resources/db
          # - egov-searcher
          # - egov-telemetry
          # - egov-user
          # - egov-user/src/main/resources/db
          # - egov-workflow-v2
          # - egov-workflow-v2/src/main/resources/db
          # - report
          # - tenant
          # - tenant/src/main/resources/db
          # - user-otp
          # - zuul
          # - internal-gateway
          # - egov-user-event
          # - egov-user-event/src/main/resources/db
          # - pdf-service
          # - pdf-service/migration
          # - egov-telemetry/egov-telemetry-kafka-streams
          # - egov-telemetry/egov-telemetry-batch-process
          # - egov-url-shortening
          # - egov-url-shortening/src/main/resources/db
          # - chatbot
          # - chatbot/src/main/resources/db
          # - http-to-kafka-connector
          # - egov-user
          # - mailbot
          # - libraries/enc-client
          # - libraries/tracer
          # - nlp-engine
          # - xstate-chatbot/nodejs
          # - xstate-chatbot/nodejs/db
          # - internal-gateway
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker and push Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/egov-accesscontrol:${{ github.sha }} -f ./build/maven/Dockerfile --build-arg WORK_DIR=./egov-accesscontrol .
        docker push ${{ secrets.DOCKER_USERNAME }}/egov-accesscontrol:${{ github.sha }}
